# Generated by Django 3.2.5 on 2022-05-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data_evento', 'nome_evento']},
        ),
    ]
