# Generated by Django 3.2.5 on 2022-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('Sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('dt_nasc', models.DateField(max_length=11, verbose_name='Data de Nascimento')),
                ('Endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('Numero', models.IntegerField(max_length=6, verbose_name='Numero')),
                ('Complemento', models.IntegerField(max_length=50, verbose_name='Numero')),
                ('celular', models.IntegerField(max_length=9, unique=True)),
                ('Intenção', models.CharField(choices=[('DOARDOR', 'DOADOR'), ('DONATÁRIO', 'DONATÁRIO')], max_length=50, verbose_name='Equipamento')),
            ],
        ),
    ]
