<<<<<<< HEAD
# Generated by Django 3.2.5 on 2022-05-25 15:18
=======
# Generated by Django 3.2.5 on 2022-06-13 16:03
>>>>>>> 18f5c8a (Criação login de usuarios, api cadastro de doadores e doação)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('Nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('Sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('dt_nasc', models.DateField(max_length=11, verbose_name='Data de Nascimento')),
                ('Endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('Numero', models.IntegerField(max_length=6, verbose_name='Numero')),
                ('Complemento', models.IntegerField(max_length=50, verbose_name='Numero')),
                ('celular', models.IntegerField(max_length=9, unique=True)),
                ('Intenção', models.CharField(choices=[('DOARDOR', 'DOADOR'), ('DONATÁRIO', 'DONATÁRIO')], max_length=50, verbose_name='Equipamento')),
=======
                ('nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('dt_nasc', models.DateField(max_length=11, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('celular', models.IntegerField(unique=True, verbose_name='Celular para Contato')),
                ('Intenção', models.CharField(choices=[('DOARDOR', 'DOADOR'), ('DONATÁRIO', 'DONATÁRIO')], max_length=50, verbose_name='Intenção')),
>>>>>>> 18f5c8a (Criação login de usuarios, api cadastro de doadores e doação)
            ],
        ),
    ]
