# Generated by Django 3.2.5 on 2022-05-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='Complemento',
            field=models.IntegerField(verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='Numero',
            field=models.IntegerField(verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='celular',
            field=models.IntegerField(unique=True, verbose_name='Celular para Contato'),
        ),
    ]
