# Generated by Django 3.2.5 on 2022-05-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0002_auto_20220525_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doadores',
            old_name='Complemento',
            new_name='complemento',
        ),
        migrations.RenameField(
            model_name='doadores',
            old_name='Endereco',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='doadores',
            old_name='Nome',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='doadores',
            old_name='Numero',
            new_name='numero',
        ),
        migrations.RenameField(
            model_name='doadores',
            old_name='Sobrenome',
            new_name='sobrenome',
        ),
    ]
