# Generated by Django 3.2.5 on 2022-05-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0003_auto_20220526_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='Intenção',
            field=models.CharField(choices=[('DOARDOR', 'DOADOR'), ('DONATÁRIO', 'DONATÁRIO')], max_length=50, verbose_name='Intenção'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='complemento',
            field=models.CharField(max_length=50, verbose_name='Complemento'),
        ),
    ]
