# Generated by Django 3.2.5 on 2022-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0004_auto_20220614_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='Estado',
            field=models.CharField(choices=[('NOVO', 'NOVO'), ('SEMI-NOVO', 'SEMI-NOVO'), ('USADO', 'USADO'), ('NAO SE APLICA AO ITEM', 'NÃO SE APLICA')], max_length=50, verbose_name='Estado de Conservação'),
        ),
    ]
