# Generated by Django 3.2.5 on 2022-06-14 11:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doadores', '0006_auto_20220614_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='Doador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
