# Generated by Django 3.2.5 on 2022-06-14 12:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doadores', '0009_alter_doacao_doador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='Doador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
