# Generated by Django 3.2.5 on 2022-06-07 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Insira o título para sua publicação.', max_length=100, unique=True, verbose_name='Título da publicação')),
                ('publicacao', models.TextField(help_text='Digite sua publicação.', unique=True, verbose_name='Publicação')),
                ('data_publicacao', models.DateTimeField(auto_now=True, help_text='Data de publicação.', verbose_name='Publicação em')),
            ],
            options={
                'db_table': 'blog',
                'ordering': ['data_publicacao', 'titulo'],
            },
        ),
    ]
