# Generated by Django 3.2.5 on 2022-06-30 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('dt_nasc', models.DateField(max_length=11, verbose_name='Data de Nascimento')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('celular', models.BigIntegerField(unique=True, verbose_name='Celular para Contato')),
                ('Intencao', models.CharField(choices=[('DOADOR', 'DOADOR'), ('DONATÁRIO', 'DONATÁRIO')], max_length=50, verbose_name='Intenção')),
                ('Doador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Classificacao', models.CharField(choices=[('ALIMENTOS NÃO PERECÍVEIS', 'ALIMENTOS NÃO PERECÍVEIS'), ('ANIMAIS', 'ANIMAIS'), ('BRINQUEDOS', 'BRINQUEDOS'), ('EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)', 'EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)'), ('ITENS DE HIGIENE PESSOAL', 'ITENS DE HIGIENE PESSOAL'), ('LIVROS', 'LIVROS'), ('MOVÉIS', 'MOVÉIS'), ('ROUPAS COMUM', 'ROUPAS COMUM'), ('ROUPAS DE FRIO E ACESSÓRIOS', 'ROUPAS DE FRIO E ACESSÓRIOS')], max_length=56, verbose_name='Estado de Conservação')),
                ('Descricao', models.CharField(max_length=50, verbose_name='Descrição do item para doação')),
                ('Estado', models.CharField(choices=[('NOVO', 'NOVO'), ('SEMI-NOVO', 'SEMI-NOVO'), ('USADO', 'USADO'), ('NAO SE APLICA AO ITEM', 'NÃO SE APLICA')], max_length=50, verbose_name='Estado de Conservação')),
                ('Quantidade', models.IntegerField(verbose_name='Quantidade de Itens')),
                ('Doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
