# Generated by Django 3.2.5 on 2022-07-01 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Primeiro Nome')),
                ('sobrenome', models.CharField(max_length=50, verbose_name='Sobrenome')),
                ('dt_nasc', models.DateField(max_length=11, verbose_name='Data de Nascimento')),
                ('cep', localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=500, verbose_name='Endereço')),
                ('numero', models.IntegerField(verbose_name='Numero')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=500, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=500, verbose_name='Cidade')),
                ('estado', localflavor.br.models.BRStateField(blank=True, max_length=2, null=True, verbose_name='Estado')),
                ('celular', models.CharField(max_length=20, unique=True, verbose_name='Celular para Contato')),
                ('Intencao', models.CharField(choices=[('DOADOR', 'DOADOR'), ('DONATÁRIO', 'DONATÁRIO')], max_length=50, verbose_name='Intenção')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Doador')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(choices=[('ALIMENTOS NÃO PERECÍVEIS', 'ALIMENTOS NÃO PERECÍVEIS'), ('ANIMAIS', 'ANIMAIS'), ('BRINQUEDOS', 'BRINQUEDOS'), ('EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)', 'EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)'), ('ITENS DE HIGIENE PESSOAL', 'ITENS DE HIGIENE PESSOAL'), ('LIVROS', 'LIVROS'), ('MOVÉIS', 'MOVÉIS'), ('ROUPAS COMUM', 'ROUPAS COMUM'), ('ROUPAS DE FRIO E ACESSÓRIOS', 'ROUPAS DE FRIO E ACESSÓRIOS')], max_length=56, verbose_name='Tipo de Doação')),
                ('descricao', models.CharField(max_length=3000, verbose_name='Descrição do item para doação')),
                ('estado', models.CharField(choices=[('NOVO', 'NOVO'), ('SEMI-NOVO', 'SEMI-NOVO'), ('USADO', 'USADO'), ('NAO SE APLICA AO ITEM', 'NÃO SE APLICA')], max_length=50, verbose_name='Estado de Conservação')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade de Itens')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Doador')),
            ],
        ),
    ]
