# Generated by Django 3.2.5 on 2022-06-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipamento', models.CharField(max_length=50, verbose_name='Item para doação')),
                ('Intenção', models.CharField(choices=[('NOVO', 'NOVO'), ('SEMI-NOVO', 'SEMI-NOVO'), ('USADO', 'USADO')], max_length=50, verbose_name='Estado de Conservação')),
                ('Quantidade', models.IntegerField(verbose_name='Quantidade de Itens')),
            ],
        ),
    ]
