# Generated by Django 3.2.5 on 2022-07-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='celular',
            field=models.CharField(max_length=15, unique=True, verbose_name='Celular para Contato'),
        ),
    ]
