# Generated by Django 3.2.5 on 2022-07-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0003_alter_doadores_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
    ]
