# Generated by Django 3.2.5 on 2022-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0003_rename_intenção_doacao_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doacao',
            name='Equipamento',
        ),
        migrations.AddField(
            model_name='doacao',
            name='Classificacao',
            field=models.CharField(choices=[('ALIMENTOS NÃO PERECÍVEIS', 'ALIMENTOS NÃO PERECÍVEIS'), ('ANIMAIS', 'ANIMAIS'), ('BRINQUEDOS', 'BRINQUEDOS'), ('EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)', 'EQUIPAMENTOS (CADEIRA DE RODAS, MULETA, ÓCULOS E ETC...)'), ('ITENS DE HIGIENE PESSOAL', 'ITENS DE HIGIENE PESSOAL'), ('LIVROS', 'LIVROS'), ('MOVÉIS', 'MOVÉIS'), ('ROUPAS COMUM', 'ROUPAS COMUM'), ('ROUPAS DE FRIO E ACESSÓRIOS', 'ROUPAS DE FRIO E ACESSÓRIOS')], default=0, max_length=56, verbose_name='Estado de Conservação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='Descricao',
            field=models.CharField(default=0, max_length=50, verbose_name='Descrição do item para doação'),
            preserve_default=False,
        ),
    ]
