# Generated by Django 3.2.5 on 2022-11-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0004_alter_doadores_cep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doadores',
            name='Intencao',
        ),
        migrations.RemoveField(
            model_name='doadores',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='doadores',
            name='sobrenome',
        ),
        migrations.AddField(
            model_name='doacao',
            name='intencao',
            field=models.CharField(choices=[('DOAR', 'DOAR'), ('RECEBER', 'RECEBER')], default='DT', max_length=50, verbose_name='Intenção do Donativo'),
            preserve_default=False,
        ),
    ]
