# Generated by Django 3.2.5 on 2022-11-19 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doadores', '0005_auto_20221105_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doadores',
            options={'ordering': ['username'], 'verbose_name': 'Doador', 'verbose_name_plural': 'Doadores'},
        ),
        migrations.AddField(
            model_name='doadores',
            name='cpf',
            field=localflavor.br.models.BRCPFField(default=0, help_text='Cadastro de Pessoa Física', max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doadores',
            name='local_referencia',
            field=models.CharField(default='Local de referÃªncia', max_length=50, verbose_name='Local de referência para facilitar a localização'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doadores',
            name='bairro',
            field=models.CharField(help_text='Insira o bairro', max_length=500, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='celular',
            field=models.CharField(help_text='Insira o número de telefone', max_length=16, unique=True, verbose_name='Celular para Contato'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(help_text='Insira o CEP', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='cidade',
            field=models.CharField(help_text='Insira a cidade', max_length=500, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='complemento',
            field=models.CharField(help_text='Insira o complemento do endereço', max_length=50, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='dt_nasc',
            field=models.DateField(help_text='Insira data de nascimento', max_length=11, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='endereco',
            field=models.CharField(help_text='Insira o endereço', max_length=500, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='estado',
            field=localflavor.br.models.BRStateField(blank=True, help_text='Insira o estado', max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='numero',
            field=models.IntegerField(help_text='Insira o número do endereço', verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='doadores',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Doador'),
        ),
    ]
