# Generated by Django 3.2.5 on 2022-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0007_alter_doadores_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='local_referencia',
            field=models.CharField(help_text='Local de referência para facilitar a localização', max_length=50, verbose_name='Local de referência'),
        ),
    ]
