# Generated by Django 3.2.5 on 2022-11-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0008_alter_doadores_local_referencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='doacao',
            name='detalhamento',
            field=models.TextField(default=1, help_text='Escreva um detalhamento do donativo', max_length=250, verbose_name='Detalhamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='matricula',
            field=models.CharField(default=1, help_text='Insira o número de matricula conforme exemplo: AAAA-999999', max_length=11, verbose_name='Número de matricula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doacao',
            name='publicar',
            field=models.BooleanField(default=False, help_text='O donativo deve ser publicado na página de doações?', verbose_name='Publicar?'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='status',
            field=models.CharField(choices=[('DOADOR', (('CDOA', 'COM DOADOR'), ('ADOA', 'AGUARDANDO ENTREGA DO DOADOR'))), ('RECEPTOR', (('CREC', 'COM RECEPTOR'), ('AREC', 'AGUARDANDO RETIRADA DO RECEPTOR'))), ('MANUTENÇÃO', (('MREP', 'NECESSITANDO REPARO'), ('MPEC', 'AGUARDANDO PEÇA'), ('MHIG', 'EM HIGIENIZAÇÃO'))), ('PROJETO', (('PDOC', 'DISPONÍVEL PARA DOAÇÃO'), ('POBS', 'OBSOLETO'))), ('UNKN', 'UNKNOWN')], default='CDOA', help_text='Qual situação o donativo se encontra?', max_length=4, verbose_name='Status'),
        ),
    ]
