# Generated by Django 3.2.5 on 2022-11-20 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0009_auto_20221120_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doacao',
            name='descricao',
            field=models.CharField(max_length=3000, verbose_name='Donativo'),
        ),
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintetica', models.CharField(help_text='Digite a classificação sintética', max_length=30, verbose_name='Classificação Sintética')),
                ('analitica', models.CharField(help_text='Digite a classificação analítica', max_length=50, verbose_name='Classificação Analítica')),
            ],
            options={
                'ordering': ['sintetica', 'analitica'],
                'unique_together': {('sintetica', 'analitica')},
            },
        ),
        migrations.AlterField(
            model_name='doacao',
            name='classificacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doadores.classificacao'),
        ),
    ]
