# Generated by Django 3.2.5 on 2022-11-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0010_auto_20221120_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doacao',
            options={'ordering': ['descricao'], 'verbose_name': 'Donativo', 'verbose_name_plural': 'Donativos'},
        ),
        migrations.AddField(
            model_name='doacao',
            name='tamanho',
            field=models.CharField(choices=[('P', 'PEQUENO'), ('M', 'MÉDIO'), ('G', 'GRANDE')], default='P', help_text='Qual o tamanho do item?', max_length=1, verbose_name='Tamanho'),
        ),
    ]
