# Generated by Django 3.2.5 on 2022-11-28 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0012_auto_20221128_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(choices=[('RECP', 'RECEPTOR ENVIOU'), ('DOAR', 'DOADOR RECEBEU')], default='RECP', help_text='Status da Mensagem', max_length=4, verbose_name='Mensagem Elos de Amos')),
                ('status_contrato', models.CharField(choices=[('ASS', 'ASSINADO'), ('DEV', 'DEVOLVIDO')], default='RECP', help_text='Doador assinou e devolveu o contrato?', max_length=3, verbose_name='Status')),
                ('donativo', models.ForeignKey(help_text='Escolho o donativo', on_delete=django.db.models.deletion.PROTECT, to='doadores.doacao', verbose_name='Donativo')),
            ],
        ),
    ]
