# Generated by Django 3.2.5 on 2022-11-28 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0013_receptor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receptor',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
    ]
