# Generated by Django 3.2.5 on 2022-11-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0014_alter_receptor_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='data_vigencia',
            field=models.DateField(default='2023-12-30', help_text='Data de vigência do contrato', verbose_name='Data'),
            preserve_default=False,
        ),
    ]
