# Generated by Django 3.2.5 on 2022-06-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doadores', '0015_alter_doacao_doador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doadores',
            name='Intenção',
            field=models.CharField(choices=[('DOADOR', 'DOADOR'), ('DONATÁRIO', 'DONATÁRIO')], max_length=50, verbose_name='Intenção'),
        ),
    ]
