# Generated by Django 3.2.5 on 2022-11-28 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doadores', '0015_receptor_data_vigencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='receptor',
            name='receptor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
    ]
