# Generated by Django 3.2.5 on 2022-06-18 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(help_text='Insira a sigla do estado.', max_length=2, unique=True, verbose_name='Sigla')),
                ('estado', models.CharField(help_text='Insira o nome do estado.', max_length=30, unique=True, verbose_name='Estado')),
                ('atende', models.BooleanField(help_text='O estado esta atendendo doações?', verbose_name='Atende Doação?')),
            ],
        ),
        migrations.CreateModel(
            name='DadoPessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_fixo', models.CharField(help_text='Insira um número para contato. Exemplo: (00) 0000-0000.', max_length=14, unique=True, verbose_name='Telefone Fixo')),
                ('telefone_celular', models.CharField(help_text='Insira um número de celular para contato. Exemplo: (00) 00000-0000.', max_length=15, unique=True, verbose_name='Telefone Celular')),
                ('endereco', models.CharField(help_text='Insira um endereço para retirada das doações.', max_length=250, verbose_name='Endereço')),
                ('numero', models.CharField(help_text='Insira o número do endereço', max_length=6, verbose_name='Número')),
                ('complemento', models.CharField(help_text='Insira um complemento ao endereço.', max_length=150, verbose_name='Complemento')),
                ('cidade', models.CharField(help_text='Insira sua cidade', max_length=150, verbose_name='Cidade que reside')),
                ('cep', models.CharField(help_text='Insira seu CEP.', max_length=9, verbose_name='CEP')),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
